package com.agnext.reporting.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.Optional;

@Getter
@AllArgsConstructor
public enum Analytics {

    MOISTURE1("moisturecontent", "MANUAL", "moistureManual"),
    MOISTURE2("moisturecontent", "VISIO-DENSITY", "moistureVisioDensity"),
    MOISTURE3("moisturecontent", "VISIO-COUNT", "moistureVisioCount"),
    FOREIGNMATTER1("foreignmatter", "MANUAL", "foreignMatterManual"),
    FOREIGNMATTER2("foreignmatter", "VISIO-DENSITY", "foreignMatterVisioDensity"),
    FOREIGNMATTER3("foreignmatter", "VISIO-COUNT", "foreignMatterVisioCount"),
    FOREIGNMATTERORGANIC1("foreignmatterorganic", "MANUAL", "foreignMatterOrganicManual"),
    FOREIGNMATTERORGANIC2("foreignmatterorganic", "VISIO-COUNT", "foreignMatterOrganicVisioCount"),
    FOREIGNMATTERORGANIC3("foreignmatterorganic", "VISIO-DENSITY", "foreignMatterOrganicVisioDensity"),
    ADMIXTURE1("admixture", "MANUAL", "admixtureManual"),
    ADMIXTURE2("admixture", "VISIO-DENSITY", "admixtureVisioDensity"),
    ADMIXTURE3("admixture", "VISIO-COUNT", "admixtureVisioCount"),
    DAMAGED1("damaged", "MANUAL", "damagedManual"),
    DAMAGED2("damaged", "VISIO-COUNT", "damagedVisioCount"),
    DAMAGED3("damaged", "VISIO-DENSITY", "damagedVisioDensity"),
    WEEVILLED1("weevilled", "MANUAL", "weevilledManual"),
    WEEVILLED2("weevilled", "VISIO-COUNT", "weevilledVisioCount"),
    WEEVILLED3("weevilled", "VISIO-DENSITY", "weevilledVisioDensity"),
    SHRIVELLEDANDIMMATURE1("shrivelledandimmature", "MANUAL", "shrivelledAndImmatureManual"),
    SHRIVELLEDANDIMMATURE2("shrivelledandimmature", "VISIO-COUNT", "shrivelledAndImmatureVisioCount"),
    SHRIVELLEDANDIMMATURE3("shrivelledandimmature", "VISIO-DENSITY", "shrivelledAndImmatureVisioDensity"),
    SLIGHTLYDAMAGED1("slightlydamaged", "MANUAL", "slightlyDamagedManual"),
    SLIGHTLYDAMAGED2("slightlydamaged", "VISIO-COUNT", "slightlyDamagedVisioCount"),
    SLIGHTLYDAMAGED3("slightlydamaged", "VISIO-DENSITY", "slightlyDamagedVisioDensity"),
    PODSOFOTHERVARIETY1("podsofothervariety", "MANUAL", "podsOfOtherVarietyManual"),
    PODSOFOTHERVARIETY2("podsofothervariety", "VISIO-COUNT", "podsOfOtherVarietyVisioCount"),
    PODSOFOTHERVARIETY3("podsofothervariety", "VISIO-DENSITY", "podsOfOtherVarietyVisioDensity"),
    SHELLING1("shelling", "MANUAL", "shellingManual"),
    SHELLING2("shelling", "VISIO-COUNT", "shellingVisioCount"),
    SHELLING3("shelling", "VISIO-DENSITY", "shellingVisioDensity"),
    DAMAGEDANDWEEVILLED1("damagedandweevilled", "MANUAL", "damagedAndWeevilledManual"),
    DAMAGEDANDWEEVILLED2("damagedandweevilled", "VISIO-COUNT", "damagedAndWeevilledVisioCount"),
    DAMAGEDANDWEEVILLED3("damagedandweevilled", "VISIO-DENSITY", "damagedAndWeevilledVisioDensity"),
    IMMATURE1("immature", "MANUAL", "immatureManual"),
    IMMATURE2("immature", "VISIO-COUNT", "immatureVisioCount"),
    IMMATURE3("immature", "VISIO-DENSITY", "immatureVisioDensity"),
    OTHERFOODGRAINS1("otherfoodgrains", "MANUAL", "otherFoodGrainsManual"),
    OTHERFOODGRAINS2("otherfoodgrains", "VISIO-COUNT", "otherFoodGrainsVisioCount"),
    OTHERFOODGRAINS3("otherfoodgrains", "VISIO-DENSITY", "otherFoodGrainsVisioDensity"),
    SMALLATROPHIEDSEEDS1("smallatrophiedseeds", "MANUAL", "smallAtrophiedSeedsManual"),
    SMALLATROPHIEDSEEDS2("smallatrophiedseeds", "VISIO-COUNT", "smallAtrophiedSeedsVisioCount"),
    SMALLATROPHIEDSEEDS3("smallatrophiedseeds", "VISIO-DENSITY", "smallAtrophiedSeedsVisioDensity"),
    SPLITCRACKED1("splitcracked", "MANUAL", "splitCrackedManual"),
    SPLITCRACKED2("splitcracked", "VISIO-COUNT", "splitCrackedVisioCount"),
    SPLITCRACKED3("splitcracked", "VISIO-DENSITY", "splitCrackedVisioDensity"),
    BLACKTIP1("blacktip", "MANUAL", "blackTipManual"),
    BLACKTIP2("blacktip", "VISIO-COUNT", "blackTipVisioCount"),
    BLACKTIP3("blacktip", "VISIO-DENSITY", "blackTipVisioDensity"),
    BROKEN1("broken", "MANUAL", "brokenManual"),
    BROKEN2("broken", "VISIO-COUNT", "brokenVisioCount"),
    BROKEN3("broken", "VISIO-DENSITY", "brokenVisioDensity"),
    BROKEN21("broken2", "MANUAL", "broken2Manual"),
    BROKEN22("broken2", "VISIO-COUNT", "broken2VisioCount"),
    BROKEN23("broken2", "VISIO-DENSITY", "broken2VisioDensity"),
    CLEAN1("clean", "MANUAL", "cleanManual"),
    CLEAN2("clean", "VISIO-COUNT", "cleanVisioCount"),
    CLEAN3("clean", "VISIO-DENSITY", "cleanVisioDensity"),
    GRAINCOUNT1("graincount", "MANUAL", "grainCountManual"),
    GRAINCOUNT2("graincount", "VISIO-COUNT", "grainCountVisioCount"),
    GRAINCOUNT3("graincount", "VISIO-DENSITY", "grainCountVisioDensity"),
    ASPECTRATIO1("aspectratio", "MANUAL", "aspectRatioManual"),
    ASPECTRATIO2("aspectratio", "VISIO-COUNT", "aspectRatioVisioCount"),
    ASPECTRATIO3("aspectratio", "VISIO-DENSITY", "aspectRatioVisioDensity"),
    LENGTH1("length", "MANUAL", "lengthManual"),
    LENGTH2("length", "VISIO-COUNT", "lengthVisioCount"),
    LENGTH3("length", "VISIO-DENSITY", "lengthVisioDensity"),
    WIDTH1("width", "MANUAL", "widthManual"),
    WIDTH2("width", "VISIO-COUNT", "widthVisioCount"),
    WIDTH3("width", "VISIO-DENSITY", "widthVisioDensity"),
    KARNALBUNT1("karnalbunt", "MANUAL", "karnalBuntManual"),
    KARNALBUNT2("karnalbunt", "VISIO-COUNT", "karnalBuntVisioCount"),
    KARNALBUNT3("karnalbunt", "VISIO-DENSITY", "karnalBuntVisioDensity"),
    REDWHEAT1("redwheat", "MANUAL", "redWheatManual"),
    REDWHEAT2("redwheat", "VISIO-COUNT", "redWheatVisioCount"),
    REDWHEAT3("redwheat", "VISIO-DENSITY", "redWheatVisioDensity"),
    FUNGUS1("fungus", "MANUAL", "fungusManual"),
    FUNGUS2("fungus", "VISIO-COUNT", "fungusVisioCount"),
    FUNGUS3("fungus", "VISIO-DENSITY", "fungusVisioDensity"),
    FUNGUSDAMAGED1("fungusdamaged", "MANUAL", "fungusDamagedManual"),
    FUNGUSDAMAGED2("fungusdamaged", "VISIO-COUNT", "fungusDamagedVisioCount"),
    FUNGUSDAMAGED3("fungusdamaged", "VISIO-DENSITY", "fungusDamagedVisioDensity"),
    WHITEFUNGUS1("whitefungus", "MANUAL", "whiteFungusManual"),
    WHITEFUNGUS2("whitefungus", "VISIO-COUNT", "whiteFungusVisioCount"),
    WHITEFUNGUS3("whitefungus", "VISIO-DENSITY", "whiteFungusVisioDensity"),
    TEMPRATURE1("temperature", "MANUAL", "temperatureManual"),
    TEMPRATURE2("temperature", "VISIO-COUNT", "temperatureVisioCount"),
    TEMPRATURE3("temperature", "VISIO-DENSITY", "temperatureVisioDensity"),
    MOISTUREWEIGHT1("moistureweight", "MANUAL", "moistureWeightManual"),
    MOISTUREWEIGHT2("moistureweight", "VISIO-COUNT", "moistureWeightVisioCount"),
    MOISTUREWEIGHT3("moistureweight", "VISIO-DENSITY", "moistureWeightVisioDensity"),
    BLACK1("black", "MANUAL", "blackManual"),
    BLACK2("black", "VISIO-COUNT", "blackVisioCount"),
    BLACK3("black", "VISIO-DENSITY", "blackVisioDensity"),
    RED1("red", "MANUAL", "redManual"),
    RED2("red", "VISIO-COUNT", "redVisioCount"),
    RED3("red", "VISIO-DENSITY", "redVisioDensity"),
    SHRIVELLED1("shrivelled", "MANUAL", "shrivelledManual"),
    SHRIVELLED2("shrivelled", "VISIO-COUNT", "shrivelledVisioCount"),
    SHRIVELLED3("shrivelled", "VISIO-DENSITY", "shrivelledVisioDensity"),
    TCW1("tcw", "MANUAL", "tcwManual"),
    TCW2("tcw", "VISIO-COUNT", "tcwVisioCount"),
    TCW3("tcw", "VISIO-DENSITY", "tcwVisioDensity"),
    RADIUS1("radius", "MANUAL", "radiusManual"),
    RADIUS2("radius", "VISIO-COUNT", "radiusVisioCount"),
    RADIUS3("radius", "VISIO-DENSITY", "radiusVisioDensity"),
    GREEN1("green", "MANUAL", "greenManual"),
    GREEN2("green", "VISIO-COUNT", "greenVisioCount"),
    GREEN3("green", "VISIO-DENSITY", "greenVisioDensity"),
    DISCOLORED1("discolored", "MANUAL", "discoloredManual"),
    DISCOLORED2("discolored", "VISIO-COUNT", "discoloredVisioCount"),
    DISCOLORED3("discolored", "VISIO-DENSITY", "discoloredVisioDensity"),
    STARCH1("starch", "MANUAL", "starchManual"),
    STARCH2("starch", "VISIO-COUNT", "starchVisioCount"),
    STARCH3("starch", "VISIO-DENSITY", "starchVisioDensity"),
    FLAKES1("flakes", "MANUAL", "flakesManual"),
    FLAKES2("flakes", "VISIO-COUNT", "flakesVisioCount"),
    FLAKES3("flakes", "VISIO-DENSITY", "flakesVisioDensity"),
    HUSK1("husk", "MANUAL", "huskManual"),
    HUSK2("husk", "VISIO-COUNT", "huskVisioCount"),
    HUSK3("husk", "VISIO-DENSITY", "huskVisioDensity"),
    WATERDAMAGED1("waterdamaged", "MANUAL", "waterDamagedManual"),
    WATERDAMAGED2("waterdamaged", "VISIO-COUNT", "waterDamagedVisioCount"),
    WATERDAMAGED3("waterdamaged", "VISIO-DENSITY", "waterDamagedVisioDensity"),
    INSECTDAMAGEDMATTER1("insectdamagedmatter", "MANUAL", "insectDamagedMatterManual"),
    INSECTDAMAGEDMATTER2("insectdamagedmatter", "VISIO-COUNT", "insectDamagedMatterVisioCount"),
    INSECTDAMAGEDMATTER3("insectdamagedmatter", "VISIO-DENSITY", "insectDamagedMatterVisioDensity"),
    SHRUNKEN1("Shrunken", "MANUAL", "shrunkenManual"),
    SHRUNKEN2("Shrunken", "VISIO-COUNT", "shrunkenVisioCount"),
    SHRUNKEN3("Shrunken", "VISIO-DENSITY", "shrunkenVisioDensity"),
    SPLITANDTHRIPSCAPSULES1("splitandthripscapsules", "MANUAL", "splitAndThripsCapsulesManual"),
    SPLITANDTHRIPSCAPSULES2("splitandthripscapsules", "VISIO-COUNT", "splitAndThripsCapsulesVisioCount"),
    SPLITANDTHRIPSCAPSULES3("splitandthripscapsules", "VISIO-DENSITY", "splitAndThripsCapsulesVisioDensity"),
    SPROUTEDWEEVILLED1("sproutedweevilled", "MANUAL", "sproutedWeevilledManual"),
    SPROUTEDWEEVILLED2("sproutedweevilled", "VISIO-COUNT", "sproutedWeevilledVisioCount"),
    SPROUTEDWEEVILLED3("sproutedweevilled", "VISIO-DENSITY", "sproutedWeevilledVisioDensity"),
    LIVEINFESTATION1("liveinfestation", "MANUAL", "liveInfestationManual"),
    LIVEINFESTATION2("liveinfestation", "VISIO-COUNT", "liveInfestationVisioCount"),
    LIVEINFESTATION3("liveinfestation", "VISIO-DENSITY", "liveInfestationVisioDensity"),
    MOLDS1("molds", "MANUAL", "moldsManual"),
    MOLDS2("molds", "VISIO-COUNT", "moldsVisioCount"),
    MOLDS3("molds", "VISIO-DENSITY", "moldsVisioDensity"),
    WHITISHSEEDS1("whitishseeds", "MANUAL", "whitishSeedsManual"),
    WHITISHSEEDS2("whitishseeds", "VISIO-COUNT", "whitishSeedsVisioCount"),
    WHITISHSEEDS3("whitishseeds", "VISIO-DENSITY", "whitishSeedsVisioDensity"),
    CHALKYGRAIN1("chalkygrain", "MANUAL", "chalkyGrainManual"),
    CHALKYGRAIN2("chalkygrain", "VISIO-COUNT", "chalkyGrainVisioCount"),
    CHALKYGRAIN3("chalkygrain", "VISIO-DENSITY", "chalkyGrainVisioDensity"),
    EMPTYSHELL1("emptyshell", "MANUAL", "emptyShellManual"),
    EMPTYSHELL2("emptyshell", "VISIO-COUNT", "emptyShellVisioCount"),
    EMPTYSHELL3("emptyshell", "VISIO-DENSITY", "emptyShellVisioDensity"),
    HULLINGRECOVERY1("hullingrecovery", "MANUAL", "hullingRecoveryManual"),
    HULLINGRECOVERY2("hullingrecovery", "VISIO-COUNT", "hullingRecoveryVisioCount"),
    HULLINGRECOVERY3("hullingrecovery", "VISIO-DENSITY", "hullingRecoveryVisioDensity"),
    UNDEHUSKEDSPLITS1("undehuskedsplits", "MANUAL", "undehuskedSplitsManual"),
    UNDEHUSKEDSPLITS2("undehuskedsplits", "VISIO-COUNT", "undehuskedSplitsVisioCount"),
    UNDEHUSKEDSPLITS3("undehuskedsplits", "VISIO-DENSITY", "undehuskedSplitsVisioDensity"),
    STONE1("stone", "MANUAL", "stoneManual"),
    STONE2("stone", "VISIO-COUNT", "stoneVisioCount"),
    STONE3("stone", "VISIO-DENSITY", "stoneVisioDensity");

    private final String analysisName;
    private final String scanType;
    private final String columnName;

    public static Optional<Analytics> getFieldByAnalysisName(String analysisName, String analysisType) {
        return Arrays.stream(Analytics.values())
                .filter(analytics -> analytics.analysisName.equals(analysisName)
                        && analytics.scanType.equals(analysisType))
                .findFirst();
    }
}
